FROM nginx

# RUN rm /etc/nginx/conf.d/default.conf

# RUN rm /etc/nginx/conf.d/examplessl.conf

# COPY content /usr/share/nginx/html

# COPY conf /etc/nginx

WORKDIR .

# COPY ./kosyachniy.com /etc/nginx/sites-available/web

# RUN ln -s /etc/nginx/sites-available/web /etc/nginx/sites-enabled

# CMD systemctl start nginx