# Pull base image
FROM python:3.8.6

# Set work directory
WORKDIR .

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1 # Выводить print в консоль Docker

# # Install system dependencies
# RUN apt update
# RUN pip install --upgrade pip

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY . .

# Settings
RUN rm sets.py
RUN cp sets.prod.py sets.py

# Run
CMD bash run.sh