version: "3.9"
services:
  db:
    image: mongo:6.0
    ports:
      - 27017:27017

  test:
    image: ${PROJECT_NAME}/test
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    depends_on:
      - db
    env_file: .env
    environment:
      WEB: http://localhost/
    volumes:
      - ./scripts:/scripts
    command: make test
