# Pull base image
FROM node:15.5.1 as web

# Set work directory
WORKDIR .

# Install dependencies
COPY ./package.json .
RUN npm install

# Copy project
COPY . .

# Settings
# If there is already one, replace it
RUN rm -f src/sets.js
RUN cp src/sets.prod.js src/sets.js

# Create build
RUN npm run build

# NGINX
FROM nginx:1.19.6
COPY --from=web /build /web/build