# Pull base image
FROM node:15.5.1 as webbb

# Set work directory
WORKDIR .

# Install dependencies
COPY ./package.json .
RUN npm install

# Copy project
COPY . .

# Settings
# Если такой уже есть - заменить
RUN rm -f src/sets.js
RUN cp src/sets.prod.js src/sets.js

# Create build
RUN npm run build

# NGINX
FROM nginx:1.19.6
COPY --from=webbb . /web