# Pull base image
FROM node:16.10 as web

# Set work directory
WORKDIR .

# Install dependencies
COPY ./package.json .
RUN npm install

# Copy project
COPY . .

# Create build
RUN npm cache clean --force
RUN npm run build

# NGINX
FROM nginx:1.21.5
COPY --from=web /build /web/build
