services:
  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - 6379:6379
    command: sh -c "redis-server --requirepass ${REDIS_PASS}"

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    env_file: ../../.env
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ${DATA_PATH}/db:/data/db
      - ${DATA_PATH}/logs/mongodb.log:/data/logs/mongodb.log
      - ../mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf

  api:
    depends_on:
      - mongo
      - redis
    environment:
      WEB: http://localhost/
    volumes:
      # For hot reload in development
      - ../../backend/app:/app
    command: bash -c "cd /app && uv run uvicorn main:app --host 0.0.0.0 --port 5000 --proxy-headers --reload"

  web:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API: http://localhost/api/
      NEXT_PUBLIC_WEB: http://localhost/
    volumes:
      # For hot reload in development
      - ../../web/public:/app/public
      - ../../web/styles:/app/styles
      - ../../web/lib:/app/lib
      - ../../web/redux:/app/redux
      - ../../web/components:/app/components
      - ../../web/pages:/app/pages
    command: npm run dev

  server:
    image: nginx:1.29
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../nginx/local.conf:/etc/nginx/nginx.conf
      - ${DATA_PATH}/load:/load
      - ${DATA_PATH}/logs:/data/logs
      - ${DATA_PATH}/sitemaps:/data/sitemaps
      - ${DATA_PATH}/sitemap.xml:/data/sitemap.xml
      - ${DATA_PATH}/robots.txt:/data/robots.txt
    ports:
      - ${EXTERNAL_PORT}:80
    depends_on:
      - api
      - web
