services:
  api:
    environment:
      WEB: http://localhost/
    volumes:
      # For hot reload in development
      - ../../api:/app
    command: bash -c "cd /app && uv run uvicorn app:app --host 0.0.0.0 --port 5000 --proxy-headers --reload"

  web:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API: http://localhost/api/
      NEXT_PUBLIC_WEB: http://localhost/
    volumes:
      # For hot reload in development
      - ../../web/public:/app/public
      - ../../web/styles:/app/styles
      - ../../web/lib:/app/lib
      - ../../web/redux:/app/redux
      - ../../web/components:/app/components
      - ../../web/pages:/app/pages
    command: npm run dev
