services:
  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017

  test:
    image: test
    build:
      context: ../../
      dockerfile: ./tests/Dockerfile
    depends_on:
      - mongo
    env_file: ../../.env
    volumes:
      - ../../scripts:/app/scripts
    command: make test
