global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: api
    static_configs:
      - targets:
        - api:5000
  - job_name: jobs
    metrics_path: /
    static_configs:
      - targets:
        - jobs:5000
  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
        - node_exporter:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
#    metric_relabel_configs:
#      - regex: "container_label_.*"
#      action: labeldrop
